// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"In_depth","status":true,"description":"In depth map.","parameters":{"Pass Region Id":"9","Block Region Id":"10"}},
{"name":"black_room","status":true,"description":"Black Room.","parameters":{"Tile Width":"48","Padding":"24","Fade Speed":"10","Black Room Color":"rgba(5,5,4,1)","Black Room Z":"9999"}},
{"name":"YEP_ItemSynthesis","status":true,"description":"v1.06 Players can now craft their own items in-game\nthrough an item synthesis system.","parameters":{"---General---":"","Synthesis Command":"调色盘","Show Command":"true","Enable Command":"true","Auto Place Command":"true","---Command Window---":"","Item Command":"调色盘","Weapon Command":"","Armor Command":"","Finish Command":"结束","Text Alignment":"center","---Status Window---":"","Collected Recipes":"","Crafted Items":"","Crafted Weapons":"","Crafted Armors":"","---List Window---":"","Equipped Recipes":"false","Mask Unknown":"false","Mask Text":"?","Mask Italic":"true","Mask Help Text":"This item has not been synthesized yet.","Ingredients Text":"颜料","Amount Text":"Quantity","Quantity Text Size":"20","---Sound---":"","Default SE":"Twine","Default Volume":"100","Default Pitch":"100","Default Pan":"0"}},
{"name":"CustomTools","status":true,"description":"使RPG Maker MV能够自动换行。","parameters":{}},
{"name":"MOG_AnimatedText","status":true,"description":"(v1.3) Apresenta multiplos textos animados.","parameters":{"Letter Space X-Axis":"13","Letter Space Y-Axis":"0"}},
{"name":"MOG_CharShatterEffect","status":true,"description":"(v1.1) Cria o efeito de shatter nos sprites dos characters.","parameters":{}},
{"name":"MOG_Credits","status":true,"description":"(v1.1) Adiciona a cena de créditos na tela de título.","parameters":{"Command Name":"版权声明","Scrolling Speed":"1.2"}},
{"name":"TileReplace","status":true,"description":"","parameters":{}},
{"name":"ULDS","status":true,"description":"Unlimited Layer Display System.","parameters":{"Default Path":"parallaxes","Default Z":"0.5"}},
{"name":"MOG_TreasurePopup","status":true,"description":"(v1.0) Apresenta o ícone e o nome do tesouro ganho.","parameters":{"Duration":"15","Fade Speed":"5","X - Axis":"0","Y - Axis":"-32","Random Movement":"false","X Speed":"0","Y Speed":"1","Font Size":"16","Icon Scale":"0.60","Treasure Space Y-Axis":"20","Zoom Effect":"false","Gold Popup":"true","Gold Icon Index":"163"}}
];
